### Weather from valid CEP

GET http://localhost:8080/api/weather/70150900



### Weather from non-existent CEP

GET http://localhost:8080/api/weather/99999999



### Weather from invalid CEP

GET http://localhost:8080/api/weather/123